[game_default]
open_bg=".jpg"
button_1="assets/optionbar1.png"
button_2="assets/optionbar2.png"
button_3="assets/optionbar3.png"
chatbar="assets/chatbar.png"
backpack_0="assets/backpack.png"
backpack_1="assets/backpack_icon1.png"
backpack_2="assets/backpack_icon2.png"
save_1="assets/save_icon1.png"
save_2="assets/save_icon2.png"
settings_1=".png"
settings_2=".png"
close_1="assets/close_1.png"
close_2="assets/close_2.png"

[player]
name="nigger"
inventory=["banana","pans",""]
[character.sean]
name="sean"
avatar="assets/sean_avatar.jpg"
default="assets/sean_tachie.jpg"
happy="assets/sean_tachie.jpg"
sad="character.png"
angry="assets/sean_tachie.jpg"
shy="assets/sean_tachie.jpg"
[item.banana]
name="banana"
description="very big banana"
icon="assets/banana.jpg"
[item.pans]
name="pans"
description="very big banana"
icon="assets/pans.png"
[scene.school]
name="school"
background="a.jpg"
[scene.TUX]
name="TUX"
background="Tux.jpg"
[event.start]
scene="school"
dialogue="happy"
[event.sad]
scene="TUX"
dialogue="happy"
[dialogue.happy]
character1="sean"
emote1="default"
text1="我有12a我A有1我有1我有1我有1我有1我有1我有1我有1我有1我有1我有1我有1wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"	
text2="我有2"	
text3="我有3"
emote2="sad"
text4="我有4"
[dialogue.happy.options.1]
text="我很棒"
next="pans"
[dialogue.happy.options.2]
text="我非常棒"
next="pans2"
[dialogue.happy.options.3]
text="我最棒"
event="sad"
[dialogue.pans]
character1="sean"
emote1="sad"
text1="nigga in pans"
[dialogue.pans2]
character1="sean"
emote1="sad"
text1="hey!"
[dialogue.bad]
character1="sean"
emote1="sad"
text1="寶貝來了 我來了 你來了嗎"
	

