```toml
[player]
name="弗蘭克"
inventory=[]

[charactar.弗蘭克]
name="弗蘭克"
describe="玩家角色"
like=0
avatar_default=".png"
avatar_happy=".png"
avatar_shy=".png"
avatar_angry=".png"
avatar_sad=".png"
tachie_default=".png"
tachie_happy=".png"
tachie_shy=".png"
tachie_angry=".png"
tachie_sad=".png"

[charactar.約翰]
name="約翰"
describe="囚犯2"
like=0

[charactar.克拉倫斯]
name="克拉倫斯"
describe="囚犯3"
like=0

[charactar.艾倫]
name="艾倫"
describe="囚犯4"
like=0

[charactar.獄警]
name="獄警"
describe="監獄守衛"
like=0

[charactar.醫生]
name="醫生"
describe="方案C"
like=0

[scene.惡魔島背景介紹]
name="惡魔島背景介紹"
background="惡魔島背景.png"

[scene.牢房]
name="牢房"
background="牢房.png"

[scene.儲藏室]
name="儲藏室"
background="儲藏室.png"

[scene.游往岸邊]
name="游往岸邊"
background="游往岸邊.png"

[event.start]
name="開始遊戲"
scene="惡魔島背景介紹"
dialogue="惡魔島背景介紹"

[dialogue.惡魔島背景介紹]
character1="旁白"
emote1="default"
text1="惡魔島監獄，位於美國舊金山灣，是一座以嚴密看管和無人能逃著稱的監獄。"
text2="這裡有全世界防護級別最高的看守設施，以及四面圍繞湍急冰冷的海灣，數十年來未有囚犯成功逃脫。"
text3="今天，你將扮演一名囚犯弗蘭克，策劃一次大膽的逃獄行動。"
next="牢房討論計畫"

[dialogue.牢房討論計畫]
character1="弗蘭克"
emote1="default"
text1="我不想一輩子待在這裡，我們需要找到一個完善的越獄計畫。你們有什麼建議？"
character2="約翰"
emote2="default"
text2="我們可以試試挖牆逃出，並且以自製充氣艇離開。"
character3="克拉倫斯"
emote3="default"
text3="水流湍急，我覺得躲在貨物裡，並且跟著駛離的船隻運出更好。"
character4="艾倫"
emote4="default"
text4="假裝生病並且離開島上到醫院就醫，再趁機逃脫！"
next="選擇逃獄方法"

[dialogue.選擇逃獄方法.options.1]
text="約翰(挖牆＋充氣艇)"
next="方案A.真實路線"

[dialogue.選擇逃獄方法.options.2]
text="克拉倫斯(躲在貨物中)"
event="流程待定"

[dialogue.選擇逃獄方法.options.3]
text="艾倫(裝病就醫)"
event="流程待定"

[event.方案A.真實路線]
name="方案A.真實路線"
scene="牢房"
dialogue="討論鑽牆方式"

[dialogue.討論鑽牆方式]
character1="弗蘭克"
emote1="default"
text1="手邊只有湯匙、硬幣和指甲刀，根本挖不開通風口"
character2="約翰"
emote2="default"
text2="我們需要搞來一台電鑽"
character3="克拉倫斯"
emote3="default"
text3="哪裡有電鑽？"
character4="艾倫"
emote4="default"
text4="儲藏室裡面有馬達零件，我想我們可以偷來製作電鑽。"
character1="弗蘭克"
emote1="default"
text5="對了，除了電鑽以外，我們需要材料把鑽開的牆隱藏以免被發現"
character2="約翰"
emote2="default"
text6="可以將紙張上塗上與牆壁相同的油漆，並在鑽孔後貼上"
character3="克拉倫斯"
emote3="default"
text7="那我們在偷馬達時一併偷取油漆！"

[dialogue.潛入儲藏室]
character1="弗蘭克"
emote1="default"
text1="我們必須說服儲藏室守衛給我們儲藏室密碼並進入借用器材。"
next="說服守衛"

[dialogue.說服守衛]
character1="弗蘭克"
emote1="default"
text1="守衛，請你告訴我們儲藏室的密碼，我們需要借用一些器材。"
next="選擇借口"

[dialogue.選擇借口.options.1]
text="我們需要進行一些日常維修"
like=["獄警", 1]
next="獲取密碼"

[dialogue.選擇借口.options.2]
text="我們有特殊的任務"
like=["獄警", -1]
next="失敗返回"

[dialogue.選擇借口.options.3]
text="我感覺身體不舒服，裡面有急救箱"
like=["獄警", 0]
next="獲取密碼"

[dialogue.獲取密碼]
character1="獄警"
emote1="default"
text1="好的，這是儲藏室的密碼，你們記住：1234。"
next="潛入儲藏室成功"

[dialogue.潛入儲藏室成功]
character1="弗蘭克"
emote1="happy"
text1="成功了，現在讓我們趕快動手製作電鑽。"

[next="進行製作"]

[event.進行製作]
name="進行製作"
scene="儲藏室"
dialogue="電鑽製作完成"

[dialogue.電鑽製作完成]
character1="約翰"
emote1="happy"
text1="一切準備就緒，讓我們開始鑽吧！"
next="選擇鑽牆時機"

[dialogue.選擇鑽牆時機.options.1]
text="好的，事不宜遲，馬上開挖吧。"
event="被發現失敗"

[dialogue.選擇鑽牆時機.options.2]
text="電鑽先放著，等到一天一次的樂器時間再挖。"
event="安全鑽牆"

[dialogue.選擇鑽牆時機.options.3]
text="等到午餐時間，唯一沒獄警巡邏的時候鑽！"
event="勉強逃脫"

[event.被發現失敗]
name="被發現失敗"
scene="牢房"
dialogue="電鑽噪音過大被發現"

[dialogue.電鑽噪音過大被發現]
character1="獄警"
emote1="angry"
text1="什麼聲音？！你們在做什麼？！"
character2="弗蘭克"
emote2="sad"
text2="我們被發現了，快收手！"
next="逃獄失敗"

[event.安全鑽牆]
name="安全鑽牆"
scene="牢房"
dialogue="安全鑽牆成功"

[dialogue.安全鑽牆成功]
character1="約翰"
emote1="happy"
text1="一切順利！終於挖通了！"
next="討論逃獄計劃"

[event.勉強逃脫]
name="勉強逃脫"
scene="牢房"
dialogue="被懷疑但勉強躲過"

[dialogue.被懷疑但勉強躲過]
character1="弗蘭克"
emote1="nervous"
text1="快，收手……我們幾乎被發現了。"
next="討論逃獄計劃"

[dialogue.討論逃獄計劃]
character1="弗蘭克"
emote1="happy"
text1="終於挖通了！"
character2="約翰"
emote2="happy"
text2="牆的另一頭是廢棄空間，我們可以用來當作秘密工作室，準備實施逃獄！"
character3="克拉倫斯"
emote3="default"
text3="正式逃獄前要做哪些準備呢？"
character4="艾倫"
emote4="default"
text4="我們需要逃離用的充氣艇，可以用雨衣、膠帶等材料製作"
character1="弗蘭克"
emote1="default"
text5="還需要假裝睡覺的假人頭！我手邊剛好有混凝土和牙膏可用來製作"
character2="約翰"
emote2="default"
text6="那我們分工開始製作吧。"
next="開始製作"

[event.開始製作]
name="開始製作"
scene="牢房"
dialogue="製作過程"

[dialogue.製作過程]
character1="旁白"
emote1="default"
text1="經過幾個月的努力，你們終於準備好了逃離惡魔島的計劃。"
next="實施逃跑"

[event.實施逃跑]
name="實施逃跑"
scene="夜晚"
dialogue="逃獄行動"

[dialogue.逃獄行動]
character1="旁白"
emote1="default"
text1="夜晚降臨，一切準備就緒，越獄行動將於今晚實施。沿著通風管爬出監獄後，你們必須逃離巡邏獄警視線並且逃離兩層鐵絲網！記住，行動不能太慢，要在天亮前完成，不然會被發現。"
next="逃獄過程1"

[dialogue.逃獄過程1]
character1="弗蘭克"
emote1="default"
text1="你們來到一處狹窄的通風管，必須一點一點挪動身體才能前進。"
next="選擇爬行方式"

[dialogue.選擇爬行方式.options.1]
text="小心翼翼地挪動，避免發出聲音。"
event="避免聲音"

[dialogue.選擇爬行方式.options.2]
text="試圖拆掉一些障礙，加快速度。"
event="拆卸障礙"

[dialogue.選擇爬行方式.options.3]
text="快速爬行，希望盡快爬完這段路。"
event="快速爬行"

[event.避免聲音]
name="避免聲音"
scene="通風管"
dialogue="避免聲音過程"

[dialogue.避免聲音過程]
character1="旁白"
emote1="default"
text1="你深吸一口氣，悄悄地移動。避免了金屬摩擦聲，但花了過多時間！血量-2.5"
next="逃獄過程2"

[event.拆卸障礙]
name="拆卸障礙"
scene="通風管"
dialogue="拆卸障礙過程"

[dialogue.拆卸障礙過程]
character1="旁白"
emote1="default"
text1="進行的過程中你弄掉了一個螺絲，發出了巨大聲響。警衛注意到了怪異！血量-5"
next="逃獄過程2"

[event.快速爬行]
name="快速爬行"
scene="通風管"
dialogue="快速爬行過程"

[dialogue.快速爬行過程]
character1="旁白"
emote1="default"
text1="你加速爬行，卻因過度匆忙，過程中你的手臂被鋼筋輕微擦傷。血量-1"
next="逃獄過程2"

[event.逃獄過程2]
name="逃獄過程2"
scene="通風管出口"
dialogue="逃離獄警視線"

[dialogue.逃離獄警視線]
character1="弗蘭克"
emote1="default"
text1="你們成功爬出通風管，接下來需要躲避巡邏的獄警。"
next="選擇逃離方式"

[dialogue.選擇逃離方式.options.1]
text="利用陰影隱藏自己，慢慢前進。"
event="利用陰影"

[dialogue.選擇逃離方式.options.2]
text="壓低身體快速奔跑。"
event="快速奔跑"

[dialogue.選擇逃離方式.options.3]
text="散開行動，各自行動破壞獄警注意力。"
event="散開行動"

[event.利用陰影]
name="利用陰影"
scene="監獄"
dialogue="利用陰影過程"

[dialogue.利用陰影過程]
character1="旁白"
emote1="default"
text1="你們利用陰影和障礙物慢慢移動，成功避免被獄警發現，但已經越來越接近天亮。血量-2.5"
next="逃獄過程3"

[event.快速奔跑]
name="快速奔跑"
scene="監獄"
dialogue="快速奔跑過程"

[dialogue.快速奔跑過程]
character1="旁白"
emote1="default"
text1="你們快速奔跑，但其中一名囚犯不小心絆倒，造成了小擦傷。血量-1"
next="逃獄過程3"

[event.散開行動]
name="散開行動"
scene="監獄"
dialogue="散開行動過程"

[dialogue.散開行動過程]
character1="旁白"
emote1="default"
text1="你們分頭行動，儘管成功分散了獄警的注意力，但其中一名夥伴被獄警發現。血量-5"
next="逃獄過程3"

[event.逃獄過程3]
name="逃獄過程3"
scene="鐵絲網"
dialogue="爬出鐵絲網"

[dialogue.爬出鐵絲網]
character1="弗蘭克"
emote1="default"
text1="最後一道障礙就是兩層鐵絲網，你們需要找到最安全的方法爬過。"
next="選擇爬鐵絲網方式"

[dialogue.選擇爬鐵絲網方式.options.1]
text="利用找到的舊布包裹鐵絲再爬。"
event="包裹鐵絲"

[dialogue.選擇爬鐵絲網方式.options.2]
text="直接爬過低處，盡量避開尖刺。"
event="低處爬過"

[dialogue.選擇爬鐵絲網方式.options.3]
text="剪破鐵絲網並穿越。"
event="剪破鐵絲網"

[event.包裹鐵絲]
name="包裹鐵絲"
scene="鐵絲網"
dialogue="包裹鐵絲網過程"

[dialogue.包裹鐵絲網過程]
character1="旁白"
emote1="default"
text1="你們找到了些舊布，仔細包裹鐵絲網，小心翼翼地爬過去，避免了任何傷害。血量-2.5"
next="逃獄過程4"

[event.低處爬過]
name="低處爬過"
scene="鐵絲網"
dialogue="低處爬過過程"

[dialogue.低處爬過過程]
character1="旁白"
emote1="default"
text1="你們小心翼翼地選擇最少尖刺的低處爬過，但還是難免被劃破手腳。血量-3"
next="逃獄過程4"

[event.剪破鐵絲網]
name="剪破鐵絲網"
scene="鐵絲網"
dialogue="剪破鐵絲網過程"

[dialogue.剪破鐵絲網過程]
character1="旁白"
emote1="default"
text1="鐵絲網很堅硬，你們花了過多的時間才完成，這時已經快天亮了。血量-3"
next="逃獄過程4"

[event.逃獄過程4]
name="逃獄過程4"
scene="海邊"
dialogue="游向對岸"

[dialogue.游向對岸]
character1="弗蘭克"
emote1="default"
text1="海上霧氣瀰漫、水流湍急且都是鯊魚，你必須想辦法滑上岸！"
next="選擇划行方式"

[dialogue.選擇划行方式.options.1]
text="保持冷靜，穩住艇身，慢慢划行。"
event="冷靜划行"

[dialogue.選擇划行方式.options.2]
text="加速划行，試圖快速甩開鯊魚。"
event="加速划行"

[dialogue.選擇划行方式.options.3]
text="試圖用木槳擊退靠近的鯊魚。"
event="擊退鯊魚"

[event.冷靜划行]
name="冷靜划行"
scene="海邊"
dialogue="冷靜划行過程"

[dialogue.冷靜划行過程]
character1="旁白"
emote1="default"
text1="你穩住艇身，保持冷靜，悄無聲息地慢慢划行，成功避免了鯊魚的攻擊，但因湍急的河流被沖離了航向。血量-3"
next="成功上岸"

[event.加速划行]
name="加速划行"
scene="海邊"
dialogue="加速划行過程"

[dialogue.加速划行過程]
character1="旁白"
emote1="default"
text1="你加速划行，然而一不小心劃傷了船隻，導致部分水進船，你費力排水，精疲力盡。血量-1.5"
next="成功上岸"

[event.擊退鯊魚]
name="擊退鯊魚"
scene="海邊"
dialogue="擊退鯊魚過程"

[dialogue.擊退鯊魚過程]
character1="旁白"
emote1="default"
text1="你試圖用木槳擊退鯊魚，但反倒驚動了更多鯊魚，導致你被鯊魚劃破手臂，血流不止。血量-5"
next="成功上岸"

[event.成功上岸]
name="成功上岸"
scene="岸邊"
dialogue="上岸成功"

[dialogue.上岸成功]
character1="弗蘭克"
emote1="happy"
text1="水流湍急且很多鯊魚，我們有驚無險成功上岸啦！"
character2="約翰"
emote2="happy"
text2="接下來才是重頭戲。如何逃亡不被發現。"
character3="艾倫"
emote3="default"
text3="只要一步做錯，就會被逮捕並關回監獄！"
character1="弗蘭克"
emote1="default"
text4="先偷一輛車開走吧。還是要分頭行動？"
