[player]
name="小明"
inventory=[]

[character.1]
name="石頭學霸"
describe="石頭學霸是一個聰明又勤奮的學生，對於科學和宇宙有著濃厚的興趣。"
like=80
1_emote1="C1_1.png"
1_emote2="C1_2.png"
1_emote3="C1_3.png"

[character.2]
name="小花"
2_describe="小花是石頭學霸的好朋友，她對於冒險充滿了好奇心，總是陪伴著石頭學霸一起探索未知的世界。"
2_emote1="C2_1.png"
2_emote2="C2_2.png"

[character.3]
name="神秘人"
describe="神秘人是一位穿著黑色斗篷的人，他總是出現在關鍵時刻，給予石頭學霸一些重要的提示。"
3_emote1="C3_1.png"
3_emote2="C3_2.png"

[item.1]
name="地圖"
description="一張標示著宇宙各個星球位置的地圖。"
icon="I1.png"

[item.2]
name="太空望遠鏡"
description="一個可以觀察遠方星球的太空望遠鏡。"
icon="I2.png"

[scene.1]
name="石頭學霸的房間"
background="S1.png"

[scene.2]
name="太空船"
background="S2.png"

[scene.3]
name="神秘星球"
background="S3.png"

[scene.4]
name="外太空"
background="S4.png"

[scene.5]
name="地球"
background="S5.png"

[event.1]
name="開場"
scene="1"
music=""
dialogue="intro"

[dialogue.intro]
text1="石頭學霸是一個對宇宙充滿好奇心的小孩，他夢想著能夠探索宇宙的奧秘。"
text2="有一天，他在家裡的書櫃上發現了一本古老的書，書裡記載著一個神秘星球的存在。"
text3="石頭學霸決定展開一場宇宙大冒險，他找到了好友小花，一起踏上了尋找神秘星球的旅程。"
event="2"

[event.2]
name="太空船出發"
scene="2"
music=""
dialogue="1"

[dialogue.1]
character1="1"
emote1="C1_1.png"
text1="石頭學霸和小花來到了太空船上，他們準備出發探索宇宙。"
character2="2"
emote2="C2_1.png"
text2="小花興奮地說道：「我們要去哪裡呢？」"
character3="1"
emote3="C1_2.png"
text3="石頭學霸拿出地圖，指著一個星球說道：「我們要去尋找這個神秘星球。」"
character4="2"
emote4="C2_2.png"
text4="小花疑惑地問道：「那我們該怎麼找到它呢？」"
event="3"

[event.3]
name="神秘人的提示"
scene="2"
music=""
dialogue="2"

[dialogue.2]
text1="就在這時，一個神秘的人出現在他們面前。"
text2="神秘人說道：「你們要找到神秘星球，就必須先找到太空望遠鏡。」"
text3="他給了石頭學霸一個提示，然後消失在了太空船的迷霧中。"
[event.4]
name="尋找太空望遠鏡"
scene="1"
music=""
dialogue="4"

[dialogue.4]
text1="石頭學霸和小花回到了石頭學霸的房間，他們開始尋找太空望遠鏡。"
text2="石頭學霸在書櫃上找到了一本關於太空望遠鏡的書，他們按照書上的指示找到了太空望遠鏡。"
text3="他們拿著太空望遠鏡回到了太空船上。"
next="4_1"

[dialogue.4_1]
text1="石頭學霸和小花拿著太空望遠鏡站在太空船的甲板上，他們開始觀察遠方的星球。"
text2="突然，他們發現了一個閃耀著光芒的星球，他們相信那就是神秘星球。"
text3="他們立刻開始了前往神秘星球的旅程。"

[event.5]
name="抵達神秘星球"
scene="3"
music=""
dialogue="5"

[dialogue.5]
text1="經過漫長的旅程，石頭學霸和小花終於抵達了神秘星球。"
text2="他們在星球上發現了許多奇特的生物和美麗的景色，他們感到非常興奮。"
text3="他們開始探索星球，希望能夠找到更多關於宇宙的秘密。"
next="5_1"

[dialogue.5_1]
text1="在星球的某個角落，他們遇到了一位神秘的生物。"
text2="神秘生物告訴他們，要解開宇宙的秘密，他們需要回到地球上。"
text3="石頭學霸和小花決定返回地球，繼續他們的冒險。"

[event.final_success]
name="成功結局"
scene="5"
music=""
dialogue="final_success"

[dialogue.final_success]
character1="1"
emote1="C1_3.png"
text1="石頭學霸和小花回到了地球，他們將自己的冒險故事分享給了大家。"
character2="2"
emote2="C2_2.png"
text2="大家都被他們的故事所感動，他們成為了學校的英雄。"
character1="1"
emote3="C1_1.png"
text3="石頭學霸和小花決定繼續探索宇宙，尋找更多的奧秘。"
character2="2"
emote4="C2_1.png"
text4="他們的宇宙大冒險才剛剛開始。"

[event.final_fail]
name="失敗結局"
scene="5"
music=""
dialogue="final_fail"

[dialogue.final_fail]
text1="石頭學霸和小花回到了地球，但他們並沒有找到神秘的答案。"
text2="他們感到非常失望，覺得自己的冒險是一場空。"
text3="然而，他們並沒有放棄，他們決定繼續努力，尋找更多的奧秘。"