[player]
name="弗蘭克"
avatar="assets/image/character/frank/avatar/avatar_frank_default.png"
describe="它是超級帥哥"

[character.frank]
name="弗蘭克"
describe="囚犯/玩家"
like=10
tachie_nervous="assets/image/character/frank/tachie/tachie_frank_nervous.png"
tachie_default="assets/image/character/frank/tachie/tachie_frank_default.png"
tachie_happy="assets/image/character/frank/tachie/tachie_frank_happy.png"
avatar_nervous="assets/image/character/frank/avatar/avatar_frank_nervous.png"
avatar_default="assets/image/character/frank/avatar/avatar_frank_default.png"
avatar_happy="assets/image/character/frank/avatar/avatar_frank_happy.png"

[character.john]
name="約翰"
describe="囚犯2"
tachie_default="assets/image/character/john/tachie/tachie_john_default.png"
avatar_default="assets/image/character/john/avatar/avatar_john_default.png"

[character.guard]
name="獄警"
describe="獄警"
tachie_default="assets/image/character/guard/tachie/tachie_guard_default.png"
tachie_angry="assets/image/character/guard/tachie/tachie_guard_angry.png"
avatar_default="assets/image/character/guard/avatar/avatar_guard_default.png"
avatar_angry="assets/image/character/guard/avatar/avatar_guard_angry.png"

[item.key]
name="鑰匙"
description="開啟儲藏室的鑰匙"
icon="assets/image/item/key.png"

[item.drill]
name="電鑽"
description="用於挖牆的電鑽"
icon="assets/image/item/drill.png"

[scene.devil_island]
name="惡魔島環境圖片"
background="assets/image/scene/land.png"

[scene.cell]
name="牢房"
background="assets/image/scene/cell.png"

[scene.storage]
name="儲藏室門口"
background="assets/image/scene/storage_door.png"

[scene.vent]
name="通風管"
background="assets/image/scene/vent.png"

[scene.outer_wall]
name="監獄外圍牆、哨塔處"
background="assets/image/scene/outer_wall.png"

[scene.sea]
name="海上+小船+鯊魚"
background="assets/image/scene/sea.png"

[scene.us_shore]
name="美國岸邊"
background="assets/image/scene/us_shore.png"

[event.start]
name="背景介紹"
scene="devil_island"
music="assets/bgm/scary.mp3"
dialogue="intro"

[dialogue.intro]
text1="惡魔島監獄，位於美國舊金山灣，是一座以嚴密看管和無人能逃著稱的監獄。"
text2="這裡有全世界防護級別最高的看守設施，以及四面圍繞湍急冰冷的海灣，數十年來未有囚犯成功逃脫。"
text3="今天，你將扮演一名囚犯弗蘭克，策劃一次大膽的逃獄行動。你能逃脫成功嗎？"
text4="改編自1962年惡魔島真實越獄故事"
event="2"

[event.2]
name="討論鑽牆方式"
scene="cell"
music="assets/bgm/nervous.mp3"
dialogue="discuss"

[dialogue.discuss]
character1="frank"
emote1="default"
nowtalk1="你"
text1="已經進來一個月了..."
emote2="nervous"
sound1="assets/sound/stun.mp3"
text2="我不想一輩子待在這裡，我們需要找到一個完善的越獄計畫。你們有什麼建議？"
character2="john"
emote3="default"
nowtalk2="約翰"
sound2="assets/sound/confirm.mp3"
text3="我們可以試試挖牆逃出，並且以自製充氣艇離開。"
character3="frank"
emote4="nervous"
nowtalk3="你"
text4="我們手邊沒有機器，根本挖不開通風口。我們需要搞來一台電鑽！"
character4="john"
emote5="default"
nowtalk4="約翰"
sound3="assets/sound/stun.mp3"
text5="哪裡有電鑽？"
character5="frank"
emote6="default"
nowtalk5="你"
text6="儲藏室裡面有馬達零件，我想我們可以偷來製作電鑽。"
character6="john"
emote7="default"
nowtalk6="約翰"
sound4="assets/sound/confirm.mp3"
text7="鑰匙在獄警身上。看來要進行”交涉”了！"
event="3"

[event.3]
name="潛入"
scene="storage"
music="assets/bgm/minor.mp3"
dialogue="get_key"

[dialogue.get_key]
text1="你要用什麼理由跟獄警索取鑰匙？"

[dialogue.get_key.options.1]
text="我們被指派進行儲藏室維修，要跟你借鑰匙"
get_item="key"
next="give_key"

[dialogue.get_key.options.2]
text="我感覺身體不舒服，裡面有急救箱"
next="guard_angry"

[dialogue.get_key.options.3]
text="我在某處藏了偷來的十萬元，借我一下鑰匙，我就分給你！"
get_item="key"
next="give_key"

[dialogue.get_key.options.4]
text="把獄警打昏，直接硬搶鑰匙"
event="caught"

[dialogue.guard_angry]
character1="guard"
emote1="angry"
nowtalk1="獄警"
sound1="assets/sound/angry.mp3"
text1="別騙了，裡面根本沒有急救箱！"
next="storage_entry"

[dialogue.give_key]
character1="guard"
emote1="default"
nowtalk1="獄警"
sound1="assets/sound/confirm.mp3"
text1="好吧，這是儲藏室的鑰匙，但你們只能進去五分鐘。"
nowtalk2=""
sound2="assets/sound/get_item.mp3"
text2="(已獲取道具：鑰匙)"
next="storage_entry"

[dialogue.storage_entry]
character1="john"
emote1="default"
nowtalk1="約翰"
text1="現在，闖入儲藏室吧！"

[dialogue.storage_entry.options.1]
text="未獲取鑰匙，無法進入儲藏室。返回前個劇情。"
event="3"

[dialogue.storage_entry.options.2]
text="用鑰匙開門偷偷闖入 (使用道具：鑰匙)"
hide_item="key"
remove_item="key"
get_item="drill"
next="get_drill"


[dialogue.get_drill]
sound1="assets/sound/get_item.mp3"
text1="(已獲取道具：鑽頭)"
event="4"

[event.4]
name="切割"
scene="cell"
music="assets/bgm/rush.mp3"
dialogue="cutting_wall"

[dialogue.cutting_wall]
character1="john"
emote1="default"
nowtalk1="約翰"
sound1="assets/sound/hmm.mp3"
text1="得到了電鑽，一切準備就緒。讓我們開始鑽吧！"

[dialogue.cutting_wall.options.1]
text="沒有電鑽，無法挖掘，返回前個劇情。"
event="3"

[dialogue.cutting_wall.options.2]
text="好的，事不宜遲，馬上開挖吧。"
hide_item="drill"
next="caught_drill"

[dialogue.cutting_wall.options.3]
text="電鑽先放著，等到一天一次的樂器時間再挖"
hide_item="drill"
next="success_drill"

[dialogue.cutting_wall.options.4]
text="等到午餐時間，唯一沒獄警巡邏的時候鑽！"
hide_item="drill"
next="suspicious_guard"

[dialogue.caught_drill]
character1="guard"
emote1="angry"
nowtalk1="獄警"
sound1="assets/sound/angry.mp3"
text1="你在做什麼？"
nowtalk2=""
text2="因為電鑽噪音過大而被發現，逃獄失敗。"
event="caught"

[dialogue.success_drill]
sound1="assets/sound/drill.mp3"
text1="大家玩樂器的噪音蓋過了鑽牆聲，經過一個月後終於挖牆成功。"
event="5"

[dialogue.suspicious_guard]
character1="guard"
emote1="angry"
nowtalk1="獄警"
sound1="assets/sound/drill.mp3"
text1="你在做什麼？"
character2="frank"
emote2="nervous"
nowtalk2="你"
sound2="assets/sound/harmonica.mp3"
text2="沒...沒什麼，我只是在練習吹口琴。"
character3="guard"
emote3="angry"
nowtalk3="獄警"
sound3="assets/sound/angry.mp3"
text3="給我注意一點！"
nowtalk4=""
text4="因為電鑽噪音過大而被獄警懷疑，還好在趕過來時及時收手，沒被發現。"
text5="鑽牆未完成，請再次選擇。"
next="cutting_wall"

[event.5]
name="實施越獄-1"
scene="vent"
music="assets/bgm/rock.mp3"
dialogue="escape_plan_1"

[dialogue.escape_plan_1]
text1="(1 month later)"
text2="夜晚降臨，一切準備就緒，越獄行動將於今晚實施。"
text3="沿著通風管爬出監獄後，你們必須逃離巡邏獄警視線並且逃離兩層鐵絲網。"
text4="記住，行動不能太慢，要在天亮前完成，不然會被發現。"
next="health_check_1"

[dialogue.health_check_1]
text1="血量選擇活動1: 爬出通風管"
text2="你們來到一處狹窄的通風管，必須一點一點挪動身體才能前進。"
text3="你現在有10滴血，接下來的幾題，選擇錯誤會扣一定的血量，血扣完就會死亡！"

[dialogue.health_check_1.options.1]
text="小心翼翼地挪動，避免發出聲音。"
like=["frank",-1]
next="careful_move"

[dialogue.health_check_1.options.2]
text="試圖拆掉一些障礙，加快速度。"
like=["frank",-5]
next="remove_obstacles"

[dialogue.health_check_1.options.3]
text="快速爬行，希望盡快爬完這段路。"
like=["frank",-1]
next="fast_crawl"

[dialogue.careful_move]
sound1="assets/sound/vent2.mp3"
text1="你深吸一口氣，悄悄地移動。避免了金屬摩擦聲，但花了過多時間！(血量-1)"
event="6"

[dialogue.remove_obstacles]
sound1="assets/sound/vent.mp3"
text1="進行的過程中你弄掉了一個螺絲，發出了巨大聲響。警衛注意到了怪異！(血量-5)"
event="6"

[dialogue.fast_crawl]
sound1="assets/sound/vent.mp3"
text1="你加速爬行，卻因過度匆忙，過程中你的手臂被鋼筋輕微擦傷。(血量-1)"
event="6"

[event.6]
name="實施越獄2"
scene="outer_wall"
music="assets/bgm/scary.mp3"
dialogue="escape_guard"

[dialogue.escape_guard]
text1="你們成功爬出通風管，接下來需要躲避戶外巡邏的獄警。"

[dialogue.escape_guard.options.1]
text="利用陰影隱藏自己，慢慢前進。"
like=["frank",-2]
next="shadow_move"

[dialogue.escape_guard.options.2]
text="壓低身體快速奔跑"
like=["frank",-3]
next="fast_run"

[dialogue.escape_guard.options.3]
text="散開行動，各自行動破壞獄警注意力。"
next="split_move"

[dialogue.shadow_move]
text1="你們利用陰影和障礙物慢慢移動，成功避免被獄警發現，但已經越來越接近天亮。(血量-2)"
event="7"

[dialogue.fast_run]
text1="差點被獄警發現，但還是平安抵達鐵絲網處。(血量-3)"
event="7"

[dialogue.split_move]
character1="guard"
emote1="angry"
nowtalk1="獄警"
sound1="assets/sound/angry.mp3"
text1="你在做什麼？"
nowtalk2=""
text2="發出過大的噪音，被獄警發現！"
event="caught"

[event.7]
name="游往岸邊"
scene="sea"
music="assets/bgm/epic.mp3"
dialogue="sea_escape"

[dialogue.sea_escape]
text1="成功逃離鐵絲網，接下來要划船離開島嶼。"
text2="海上霧氣瀰漫、水流湍急且都是鯊魚，你必須想辦法滑上岸！"

[dialogue.sea_escape.options.1]
text="保持冷靜，穩住艇身，慢慢划行。"
like=["frank",-3]
next="calm_row"

[dialogue.sea_escape.options.2]
text="加速划行，試圖快速甩開鯊魚。"
like=["frank",-1]
next="fast_row"

[dialogue.sea_escape.options.3]
text="試圖用木槳擊退靠近的鯊魚。"
like=["frank",-5]
next="paddle_shark"

[dialogue.calm_row]
text1="你穩住艇身，保持冷靜，悄無聲息地慢慢划行，成功避免了鯊魚的攻擊，但因湍急的河流被沖離了航向。(血量-3)"
event="8"

[dialogue.fast_row]
text1="你加速划行，然而一不小心劃傷了船隻，導致部分水進船，你費力排水，精疲力盡。(血量-1)"
event="8"

[dialogue.paddle_shark]
text1="你試圖用木槳擊退鯊魚，但反倒驚動了更多鯊魚，導致你被鯊魚劃破手臂，血流不止。(血量-5)"
event="8"

[event.8]
name="成功上岸？"
scene="us_shore"
music="assets/bgm/happy.mp3"
dialogue="shore"

[dialogue.shore]
text1="到了岸邊，能否成功上岸呢？"

[dialogue.shore.options.1]
text="成功上岸！"
hide_like_bigger=["frank",0]
next="success_landing"

[dialogue.shore.options.2]
text="你已經筋疲力盡，溺死了！"
hide_like_smaller=["frank",0]
event="die"

[dialogue.success_landing]
character1="frank"
emote1="happy"
nowtalk1="你"
sound1="assets/sound/laugh.mp3"
text1="水流湍急且很多鯊魚，我們有驚無險成功上岸啦！(開心)"
character2="john"
emote2="default"
nowtalk2="約翰"
sound2="assets/sound/hmm.mp3"
text2="接下來才是重頭戲。如何逃亡不被發現。"
character3="frank"
emote3="nervous"
nowtalk3="你"
sound3="assets/sound/confirm.mp3"
text3="只要一步做錯，就會被逮捕並關回監獄！(緊張)"
character4="john"
emote4="default"
nowtalk4="約翰"
sound4="assets/sound/stun.mp3"
text4="先偷一輛車開走吧。還是要分頭行動？"
end="成功逃脫了"

[event.die]
name="死亡"
scene="us_shore"
music="assets/bgm/sad.mp3"
dialogue="die"


[dialogue.die]
text1="逃亡過程死亡，逃獄失敗，遊戲結束。"
end="你死了"

[event.caught]
name="被抓回"
scene="cell"
music="assets/bgm/sad2.mp3"
dialogue="caught_dialogue"


[dialogue.caught_dialogue]
text1="你被抓回牢房，逃獄失敗。遊戲結束。"
end="你被抓住了"
