[player]
name="罘來客"
avatar="assets/sean_avatar.jpg"
describe="它是超級帥哥"

[character.sean]
name="sean"
describe="他是世界最帥氣的男人"
avatar_default="assets/sean_avatar.jpg"
avatar_happy="assets/sean_avatar.jpg"
avatar_sad="assets/sean_avatar.jpg"
avatar_angry="assets/sean_avatar.jpg"
avatar_shy="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"

[character.roger]
name="roger"
avatar_default="assets/sean_avatar.jpg"
avatar_happy="assets/sean_avatar.jpg"
avatar_sad="assets/sean_avatar.jpg"
avatar_angry="assets/sean_avatar.jpg"
avatar_shy="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"
like=100
[character.amy]
name="amy"
avatar_default="assets/sean_avatar.jpg"
avatar_happy="assets/sean_avatar.jpg"
avatar_sad="assets/sean_avatar.jpg"
avatar_angry="assets/sean_avatar.jpg"
avatar_shy="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"
like=250

[item.banana]
name="banana"
description="這是一根超級巨大的香蕉very big banana"
icon="assets/banana.jpg"
[item.pans]
name="pans"
description="nigga in pans"
icon="assets/pans.png"
[scene.school]
name="school"
background="a.jpg"
[scene.TUX]
name="TUX"
background="Tux.jpg"
[event.start]
name="第一幕"
scene="school"
dialogue="happy"
music="assets/sound/chillin.mp3"
[event.sad]
name="第二幕"
scene="TUX"
dialogue="happy"
music="assets/sound/chillin.mp3"
[dialogue.happy]
character1="sean"
emote1="default"
nowtalk1="石頭"
text1="哇！今天天氣真好呢！風和日麗，風光明媚，好多小鳥在天上，一直唱歌123123~~123123~~"	
sound1="assets/sound/button.wav"
sound2="assets/sound/button.wav"
text2="吃我一拳！"	
text3="開玩笑的啦！"
emote2="sad"
nowtalk2="狐狸"
text4="要不要一起去野餐呢？"
[dialogue.happy.options.1]
text="不要"
next="pans"
like=["roger",-12]
[dialogue.happy.options.2]
text="我不要！"
next="pans2"
[dialogue.happy.options.3]
hide_like=["roger",90]
text="好阿"
next="pans"
[dialogue.happy.options.4]
text="現在就去！"
event="sad"
like=["roger",-12]
get_item="banana"
[dialogue.happy.options.5]
hide_item="banana"
remove_item="banana"
text="現在就去8！"
event="sad"
[dialogue.pans]
character1="sean"
emote1="sad"
text1="nigga in pans"
end="好結局"
[dialogue.pans2]
character1="sean"
emote1="sad"
text1="hey!"
[dialogue.bad]
character1="sean"
emote1="sad"
text1="寶貝來了 我來了 你來了嗎"
	

