#[玩家]
[player]
name="佛蘭克"
avatar="assets/sean_avatar.jpg"
describe="因為太帥被關入美國最嚴密的監獄"

#[角色]
[character.roger]
name="羅傑"
describe="哥噁•D•羅傑，曾經是海上最強的王者。"
like=10
avatar_default="assets/sean_avatar.jpg"
avatar_happy="assets/sean_avatar.jpg"
avatar_sad="assets/sean_avatar.jpg"
avatar_angry="assets/sean_avatar.jpg"
avatar_shy="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"

[character.amy]
name="愛咪"
like=10
describe="她是愛咪，很會畫畫"
avatar_default="assets/sean_avatar.jpg"
avatar_happy="assets/sean_avatar.jpg"
avatar_sad="assets/sean_avatar.jpg"
avatar_angry="assets/sean_avatar.jpg"
avatar_shy="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"

[character.clorans]
name="克拉倫斯"
like=10
describe="克拉倫斯，是個英國人"
avatar_default="assets/sean_avatar.jpg"
avatar_happy="assets/sean_avatar.jpg"
avatar_sad="assets/sean_avatar.jpg"
avatar_angry="assets/sean_avatar.jpg"
avatar_shy="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"

[character.police]
name="獄警"
describe="他是獄警"
like=10
avatar_default="assets/sean_avatar.jpg"
avatar_happy="assets/sean_avatar.jpg"
avatar_sad="assets/sean_avatar.jpg"
avatar_angry="assets/sean_avatar.jpg"
avatar_shy="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"

[character.doctor]
name="醫生"
describe="他是醫生"
like=10
avatar_default="assets/sean_avatar.jpg"
avatar_happy="assets/sean_avatar.jpg"
avatar_sad="assets/sean_avatar.jpg"
avatar_angry="assets/sean_avatar.jpg"
avatar_shy="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"

#[物品]

[item.key]
name="鑰匙"
description="這是一個鑰匙"
icon="assets/banana.jpg"

#[場景]
#惡魔島
[scene.demonIsland]
name="惡魔島"
background="a.jpg"
#牢房
[scene.cell]
name="牢房"
background="a.jpg"
#岸邊
[scene.bank]
name="岸邊"
background="a.jpg"
#家鄉
[scene.hometown]
name="家鄉"
background="a.jpg"
#儲藏室
[scene.storage]
name="儲藏室"
background="a.jpg"


#[開始劇本]
#介紹惡魔島
[event.start]
name="介紹"
scene="demonIsland"
dialogue="intro"
music=""

[dialogue.intro]
text1="惡魔島監獄，位於美國舊金山灣，是一座以嚴密看管和無人能逃著名的監獄。"
text2="這裡有全世界防護級別最高的看守設施，以及四面環繞湍急冰冷的海灣，數十年來未有囚犯成功逃脫。"
text3="你叫做佛蘭克，你現在正在策劃一場大膽的逃獄企劃。"
event="first_discuss"

[event.first_discuss]
name="第一次討論"
scene="cell"
dialogue="first_discuss_1"
music="assets/sound/chillin.mp3"

[dialogue.first_discuss_1]
nowtalk1="你"
text1="待在這個監獄已經一個月了..."
text2="我無法想像一輩子都要待在這裡！"
text3="我們需要一個完善的逃獄計畫"
text4="你們有什麼建議嗎？"
character1="roger"
emote1="default"
nowtalk2="羅傑"
text5="我們可以試試看挖牆壁逃出！"
text6="並用自製的充氣水挺離開！"
character2="amy"
nowtalk3="愛咪"
text7="水流很湍急，我覺得躲在貨物裡，並且跟著使離的船隻運出更好"
character3="clorans"
nowtalk4="克拉倫斯"
text8="不如假裝生病並且離開島上到醫院就醫，在趁機逃脫！"
nowtalk5=""
text9="你要選擇哪個方案呢？"
[dialogue.first_discuss_1.options.1]
text="挖牆壁方案"
next="boat_1"
[dialogue.first_discuss_1.options.2]
text="躲貨物方案"
event="goods"
[dialogue.first_discuss_1.options.3]
text="裝病方案"
event="sick"

[dialogue.boat_1]
nowtalk1="你"
text1="我覺得挖牆壁坐船還不錯"
nowtalk2="羅傑"
character1="roger"
emote1="default"
text2="那就這麼決定了！"







