[game_default]
#起始畫面
open_bg="assets/open_bg.jpg"
open_title="assets/open_title.png"
#對話框
chatbar="assets/chatbar.png"
#背包 bg背景 1背包圖示 2互動背包圖示
backpack_bg="assets/backpack.png"
backpack_1="assets/backpack_icon1.png"
backpack_2="assets/backpack_icon2.png"
#儲存 bg背景 1儲存圖示 2互動儲存圖示
save_bg="assets/backpack.png"
save_1="assets/save_icon1.png"
save_2="assets/save_icon2.png"
#載入 bg背景 1儲存圖示 2互動儲存圖示
load_bg="assets/backpack.png"
load_1="assets/save_icon1.png"
load_2="assets/save_icon2.png"
#設定  0背景 1設定圖示 2互動設定圖示
settings_1=".png"
settings_2=".png"
#關閉 1關閉圖示 2互動關閉圖示
close_1="assets/close_1.png"
close_2="assets/close_2.png"
#預設按鈕 1按鈕圖 2互動邊框 3邊框
default_button_1="assets/optionbar1.png"
default_button_2="assets/optionbar2.png"
default_button_3="assets/optionbar3.png"
#起始按鈕 1按鈕圖 2互動邊框 3邊框
open_button_1="assets/optionbar1.png"
open_button_2="assets/optionbar2.png"
open_button_3="assets/optionbar3.png"
#背包按鈕 1按鈕圖 2互動邊框 3邊框
backpack_button_1="assets/optionbar1.png"
backpack_button_2="assets/optionbar2.png"
backpack_button_3="assets/optionbar3.png"
#儲存按鈕 1按鈕圖 2互動邊框 3邊框
save_button_1="assets/optionbar1.png"
save_button_2="assets/optionbar2.png"
save_button_3="assets/optionbar3.png"

[player]
name="nigger"
inventory=["banana","pans",""]
[character.sean]
name="sean"
avatar="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"
like=10
[character.roger]
name="roger"
avatar="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"
like=100
[character.amy]
name="amy"
avatar="assets/sean_avatar.jpg"
tachie_default="assets/sean_tachie.jpg"
tachie_happy="assets/sean_tachie.jpg"
tachie_sad="character.png"
tachie_angry="assets/sean_tachie.jpg"
tachie_shy="assets/sean_tachie.jpg"
like=250
[item.banana]
name="banana"
description="very big banana"
icon="assets/banana.jpg"
[item.pans]
name="pans"
description="very big banana"
icon="assets/pans.png"
[scene.school]
name="school"
background="a.jpg"
[scene.TUX]
name="TUX"
background="Tux.jpg"
[event.start]
name="第一幕"
scene="school"
dialogue="happy"
[event.sad]
name="第二幕"
scene="TUX"
dialogue="happy"
[dialogue.happy]
character1="sean"
emote1="default"
text1="我有12a我A有1我有1我有1我有1我有1我有1我有1我有1我有1我有1我有1我有1wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww"	
text2="我有2"	
text3="我有3"
emote2="sad"
text4="我有4"
[dialogue.happy.options.1]
text="我很棒"
next="pans"
like=["roger",-12]
[dialogue.happy.options.2]
text="我非常棒"
next="pans2"
[dialogue.happy.options.3]
hide=["roger",90]
text="我很棒"
next="pans"
like=["roger",-12]
[dialogue.happy.options.4]
text="我最棒"
event="sad"
[dialogue.pans]
character1="sean"
emote1="sad"
text1="nigga in pans"
[dialogue.pans2]
character1="sean"
emote1="sad"
text1="hey!"
[dialogue.bad]
character1="sean"
emote1="sad"
text1="寶貝來了 我來了 你來了嗎"
	

